name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.134.0/hugo_0.134.0_Linux-64bit.tar.gz
          tar -xzf hugo_0.134.0_Linux-64bit.tar.gz
          mv hugo /usr/local/bin/
      - name: Build Hugo
        run: hugo --minify
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
